### ISSUE TITLE
Question: Is this library designed to be thread safe?

### ISSUE THREAD

**Issue by JanBeelte** [hendriknielaender/zlog#15]
Hello again,

I will be using the logger in combination with some multi-threaded workloads using:
https://github.com/mitchellh/libxev

Will this library be a good fit to log debug messages from multiple threads to a central place?

Best,

Jan

**Comment by hendriknielaender** [comment]
Hey @JanBeelte,

this lib will be thread safe in the future. Currently I won't recommend this library. Please use something more mature like https://github.com/karlseguin/log.zig .

This should be thread safe, hope this helps. I have one open issue which will tackle a redesign.

**Comment by JanBeelte** [comment]
Hey @hendriknielaender! 
Thanks a lot for the quick response.
I had two more options on the table:
1. https://github.com/karlseguin/log.zig
2. https://github.com/chrischtel/nexlog

currently I am leaning towards 2. but still need to figure out some details.

Good luck with the redesign, let me know when you need some feedback!

Best,

Jan
